# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\x12\x11TestTask.Messages\"\"\n\x07Request\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0b\n\x03req\x18\x02 \x02(\x05\"#\n\x08Response\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0b\n\x03res\x18\x02 \x02(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=37
  _REQUEST._serialized_end=71
  _RESPONSE._serialized_start=73
  _RESPONSE._serialized_end=108
# @@protoc_insertion_point(module_scope)
